default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: collaborative_gif_cloud_development

test:
  <<: *default
  database: collaborative_gif_cloud_test

production:
  <<: *default
  database: collaborative_gif_cloud_production
