# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

local: &local
  ceph_access_key: <%= Rails.application.config_for(:ceph)[:access_key] %>
  ceph_secret_key: <%= Rails.application.config_for(:ceph)[:secret_key] %>

development:
  <<: *local
  secret_key_base: bb3c1e5f0a2f7c3377776886ca3122c51dd320b3ce61e5d564f92053812da056068520975a196b9ebcb00a8fe9083223a7c838f364c15dd230370543d5666031

test:
  <<: *local
  secret_key_base: 618055aea3ed6ebbceb11d14448029f89e1d98591d4ec95c2807c07f9444e53eeb01516921d14d18a6baf41582eaec38f514d00c80e430703fd5447158412545

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  ceph_access_key: <%= ENV["CEPH_ACCESS_KEY"] %>
  ceph_secret_key: <%= ENV["CEPH_SECRET_KEY"] %>
